name: 'esbuild'
description: 'Builds some javascript using the master branch of https://github.com/evanw/esbuild'
inputs:	
  files:
    description: >
      A whitespace-separated(!) list of files to be minified.
    required: true
    default: 'main.js'
runs:
  using: 'docker'
  image: 'Dockerfile'
